name: weather_data_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Bạn có thể đổi thành phiên bản Python bạn đang dùng (3.9, 3.10, 3.11)
  - pip
  # Thư viện cho API và Data
  - flask
  - flask-cors
  - pandas
  - numpy
  # Thư viện Vẽ biểu đồ
  - matplotlib
  - seaborn
  # Cài đặt qua pip các gói không có sẵn trên conda
  - pip:
    - openmeteo-requests
    - requests-cache
    - retry-requests
    - pyspark